//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TALLERERP_A01_DATOSEntities : DbContext
    {
        public TALLERERP_A01_DATOSEntities()
            : base("name=TALLERERP_A01_DATOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sdm_v_fac_cab> sdm_v_fac_cab { get; set; }
        public virtual DbSet<sdm_v_fac_iv> sdm_v_fac_iv { get; set; }
        public virtual DbSet<sdm_v_fac_lin> sdm_v_fac_lin { get; set; }
    }
}
