//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdm_v_fac_lin
    {
        public string codigoPrincipal { get; set; }
        public string codigoAuxiliar { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> precioTotalSinImpuesto { get; set; }
        public Nullable<int> codigo { get; set; }
        public Nullable<int> codigoPorcentaje { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public Nullable<decimal> baseImponible { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string detAdicionalNombre1 { get; set; }
        public string detAdicionalValor1 { get; set; }
        public string detAdicionalNombre2 { get; set; }
        public string detAdicionalValor2 { get; set; }
        public string detAdicionalNombre3 { get; set; }
        public string detAdicionalValor3 { get; set; }
        public int xnumdoc_id { get; set; }
        public string xtipodoc_id { get; set; }
        public string xseccion_id { get; set; }
        public string xempresa_id { get; set; }
        public short xciclo_id { get; set; }
    }
}
