//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdm_v_fac_iv
    {
        public Nullable<decimal> baseImponible { get; set; }
        public Nullable<decimal> valor { get; set; }
        public int codigo { get; set; }
        public Nullable<int> codigoPorcentaje { get; set; }
        public Nullable<int> descuentoAdicional { get; set; }
        public string xempresa_id { get; set; }
        public string xseccion_id { get; set; }
        public string xtipodoc_id { get; set; }
        public short xciclo_id { get; set; }
        public int xnumdoc_id { get; set; }
        public Nullable<decimal> tarifa { get; set; }
    }
}
