//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdm_v_fac_cab
    {
        public string razonSocial { get; set; }
        public string nombreComercial { get; set; }
        public string ruc { get; set; }
        public string codDoc { get; set; }
        public string estab { get; set; }
        public string ptoEmi { get; set; }
        public string secuencial { get; set; }
        public string dirMatriz { get; set; }
        public string fechaEmision { get; set; }
        public string dirEstablecimiento { get; set; }
        public string contribuyenteEspecial { get; set; }
        public string obligadoContabilidad { get; set; }
        public string tipoIdentificacionComprador { get; set; }
        public string guiaRemision { get; set; }
        public string razonSocialComprador { get; set; }
        public string identificacionComprador { get; set; }
        public string direccionComprador { get; set; }
        public Nullable<decimal> totalSinImpuestos { get; set; }
        public Nullable<decimal> totalDescuento { get; set; }
        public Nullable<decimal> propina { get; set; }
        public Nullable<decimal> importeTotal { get; set; }
        public string moneda { get; set; }
        public string formaPago { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<short> plazo { get; set; }
        public string unidadTiempo { get; set; }
        public Nullable<decimal> valorRetIva { get; set; }
        public Nullable<decimal> valorRetRenta { get; set; }
        public string infoAdicionalNombre1 { get; set; }
        public string infoAdicionalValor1 { get; set; }
        public string infoAdicionalNombre2 { get; set; }
        public string infoAdicionalValor2 { get; set; }
        public string infoAdicionalNombre3 { get; set; }
        public string infoAdicionalValor3 { get; set; }
        public string infoAdicionalNombre4 { get; set; }
        public string infoAdicionalValor4 { get; set; }
        public string infoAdicionalNombre5 { get; set; }
        public string infoAdicionalValor5 { get; set; }
        public string infoAdicionalNombre6 { get; set; }
        public string infoAdicionalValor6 { get; set; }
        public string infoAdicionalNombre7 { get; set; }
        public Nullable<int> infoAdicionalValor7 { get; set; }
        public string infoAdicionalNombre8 { get; set; }
        public Nullable<int> infoAdicionalValor8 { get; set; }
        public string infoAdicionalNombre9 { get; set; }
        public Nullable<int> infoAdicionalValor9 { get; set; }
        public string infoAdicionalNombre10 { get; set; }
        public Nullable<int> infoAdicionalValor10 { get; set; }
        public string infoAdicionalNombre11 { get; set; }
        public Nullable<int> infoAdicionalValor11 { get; set; }
        public string infoAdicionalNombre12 { get; set; }
        public Nullable<int> infoAdicionalValor12 { get; set; }
        public int xnumdoc_id { get; set; }
        public string xtipodoc_id { get; set; }
        public string xseccion_id { get; set; }
        public string xempresa_id { get; set; }
        public short xciclo_id { get; set; }
        public string Estado { get; set; }
        public string preClaveAcceso { get; set; }
    }
}
